### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by silverweed** [faiface/gogame#2]
Nice work on this, it'd be super awesome to be able to write games in Go someday soon ;)

If you want people to be able to use your library, though, you'd need to add a license somewhere, like in a LICENSE file or in the README.

**Comment by faiface** [comment]
Thanks! However, my work on this library is discontinued (as noted in README) im favor of a new library called Pixel: https://github.com/faiface/pixel

I'm working heavily on this new library and haven't announced it yet, but that'll happen soon when I finish some things. 

The library is already quite usable nonetheless and is much better, flexible and more general than Gogame. You can check it out!

If you still want a LICENCE here, please let me know and I'll add it.

**Comment by silverweed** [comment]
Thanks, I didn't pay enough attention to the readme I guess, I'll check that lib out :-)
